import type { Building } from "@/lib/types";

const STAMP = "2026-09-01T00:00:00.000Z";

export const BUILDINGS: Building[] = [
  {
    id: "ghc",
    name: "Gates Hillman Center",
    short_name: "GHC",
    aliases: [
      "ghc",
      "gates",
      "gates hillman",
      "gates center",
      "gates-hillman",
      "hillman",
      "gates hillman center",
    ],
    latitude: 40.44385,
    longitude: -79.94455,
    campus_zone: "morewood",
    off_campus: false,
    geojson_feature_id: "ghc",
    height_meters: 42,
    footprint_width_m: 72,
    footprint_height_m: 58,
    created_at: STAMP,
    updated_at: STAMP,
  },
  {
    id: "tepper",
    name: "Tepper Quad",
    short_name: "Tepper",
    aliases: [
      "tepper",
      "tep",
      "tepper quad",
      "tepper school",
      "simmons",
      "simmons auditorium",
      "tepper simmons auditorium",
    ],
    latitude: 40.44125,
    longitude: -79.94195,
    campus_zone: "forbes",
    off_campus: false,
    geojson_feature_id: "tepper",
    height_meters: 28,
    footprint_width_m: 90,
    footprint_height_m: 70,
    created_at: STAMP,
    updated_at: STAMP,
  },
  {
    id: "cuc",
    name: "Cohon University Center",
    short_name: "CUC",
    aliases: [
      "cuc",
      "cohon",
      "university center",
      "cohon university center",
      "rangos",
      "rangos ballroom",
      "cuc rangos",
    ],
    latitude: 40.44295,
    longitude: -79.94175,
    campus_zone: "cut",
    off_campus: false,
    geojson_feature_id: "cuc",
    height_meters: 22,
    footprint_width_m: 80,
    footprint_height_m: 64,
    created_at: STAMP,
    updated_at: STAMP,
  },
  {
    id: "wean",
    name: "Wean Hall",
    short_name: "Wean",
    aliases: ["wean", "weh", "wean hall"],
    latitude: 40.44265,
    longitude: -79.94585,
    campus_zone: "morewood",
    off_campus: false,
    geojson_feature_id: "wean",
    height_meters: 36,
    footprint_width_m: 55,
    footprint_height_m: 70,
    created_at: STAMP,
    updated_at: STAMP,
  },
  {
    id: "doherty",
    name: "Doherty Hall",
    short_name: "DH",
    aliases: ["doherty", "dh", "doherty hall"],
    latitude: 40.44248,
    longitude: -79.9444,
    campus_zone: "morewood",
    off_campus: false,
    geojson_feature_id: "doherty",
    height_meters: 30,
    footprint_width_m: 50,
    footprint_height_m: 62,
    created_at: STAMP,
    updated_at: STAMP,
  },
  {
    id: "hunt",
    name: "Hunt Library",
    short_name: "Hunt",
    aliases: ["hunt", "hl", "hunt library"],
    latitude: 40.4411,
    longitude: -79.9437,
    campus_zone: "cut",
    off_campus: false,
    geojson_feature_id: "hunt",
    height_meters: 46,
    footprint_width_m: 48,
    footprint_height_m: 48,
    created_at: STAMP,
    updated_at: STAMP,
  },
  {
    id: "nsh",
    name: "Newell-Simon Hall",
    short_name: "NSH",
    aliases: [
      "nsh",
      "newell-simon",
      "newell simon",
      "newell simon hall",
      "newell-simon hall",
    ],
    latitude: 40.4435,
    longitude: -79.94565,
    campus_zone: "morewood",
    off_campus: false,
    geojson_feature_id: "nsh",
    height_meters: 32,
    footprint_width_m: 60,
    footprint_height_m: 50,
    created_at: STAMP,
    updated_at: STAMP,
  },
  {
    id: "hamburg",
    name: "Hamburg Hall",
    short_name: "HBH",
    aliases: ["hamburg", "hbh", "hamburg hall"],
    latitude: 40.44422,
    longitude: -79.94505,
    campus_zone: "morewood",
    off_campus: false,
    geojson_feature_id: "hamburg",
    height_meters: 24,
    footprint_width_m: 58,
    footprint_height_m: 42,
    created_at: STAMP,
    updated_at: STAMP,
  },
  {
    id: "posner",
    name: "Posner Hall",
    short_name: "Posner",
    aliases: ["posner", "posner hall", "gsia"],
    latitude: 40.44115,
    longitude: -79.94285,
    campus_zone: "forbes",
    off_campus: false,
    geojson_feature_id: "posner",
    height_meters: 20,
    footprint_width_m: 44,
    footprint_height_m: 36,
    created_at: STAMP,
    updated_at: STAMP,
  },
  {
    id: "scott",
    name: "Scott Hall",
    short_name: "Scott",
    aliases: ["scott", "scott hall"],
    latitude: 40.44315,
    longitude: -79.94655,
    campus_zone: "west",
    off_campus: false,
    geojson_feature_id: "scott",
    height_meters: 28,
    footprint_width_m: 42,
    footprint_height_m: 36,
    created_at: STAMP,
    updated_at: STAMP,
  },
  {
    id: "ansys",
    name: "ANSYS Hall",
    short_name: "ANSYS",
    aliases: ["ansys", "ansys hall"],
    latitude: 40.44238,
    longitude: -79.94665,
    campus_zone: "west",
    off_campus: false,
    geojson_feature_id: "ansys",
    height_meters: 26,
    footprint_width_m: 40,
    footprint_height_m: 34,
    created_at: STAMP,
    updated_at: STAMP,
  },
  {
    id: "porter",
    name: "Porter Hall",
    short_name: "Porter",
    aliases: ["porter", "porter hall"],
    latitude: 40.44182,
    longitude: -79.94635,
    campus_zone: "west",
    off_campus: false,
    geojson_feature_id: "porter",
    height_meters: 24,
    footprint_width_m: 48,
    footprint_height_m: 32,
    created_at: STAMP,
    updated_at: STAMP,
  },
  {
    id: "baker",
    name: "Baker Hall",
    short_name: "Baker",
    aliases: ["baker", "baker hall"],
    latitude: 40.44155,
    longitude: -79.94545,
    campus_zone: "morewood",
    off_campus: false,
    geojson_feature_id: "baker",
    height_meters: 22,
    footprint_width_m: 70,
    footprint_height_m: 28,
    created_at: STAMP,
    updated_at: STAMP,
  },
  {
    id: "craig",
    name: "Craig Street (off campus)",
    short_name: "Craig",
    aliases: ["craig", "craig street", "off campus", "shadyside"],
    latitude: 40.4514,
    longitude: -79.9618,
    campus_zone: "off_campus",
    off_campus: true,
    geojson_feature_id: "craig",
    height_meters: 12,
    footprint_width_m: 28,
    footprint_height_m: 22,
    created_at: STAMP,
    updated_at: STAMP,
  },
];

export const BUILDING_BY_ID: Record<string, Building> = Object.fromEntries(
  BUILDINGS.map((b) => [b.id, b]),
);

export function getBuilding(id: string | null | undefined): Building | null {
  if (!id) return null;
  return BUILDING_BY_ID[id] ?? null;
}
